import { renderPdf } from './pdf.js'

/**
 * The welcome note as a PDF (plan 050): the database builds the text
 * (welcome_note_render); this lays it out — a heading line, the sections
 * the text already carries as short lines, and the sign-off.
 */
export type WelcomeNoteData = { company: string; subject: string; lines: string[] }

const HEADINGS = new Set(['Your first day', 'Our policies'])

export async function renderWelcomeNote(data: WelcomeNoteData): Promise<Buffer> {
  const content: Record<string, unknown>[] = [
    { text: data.company, fontSize: 9, color: '#666' },
    { text: data.subject, fontSize: 16, bold: true, margin: [0, 4, 0, 14] },
  ]
  for (const line of data.lines) {
    if (line === '') content.push({ text: ' ', fontSize: 6 })
    else if (HEADINGS.has(line)) content.push({ text: line, bold: true, margin: [0, 6, 0, 4] })
    else content.push({ text: line, margin: [0, 0, 0, 2] })
  }
  content.push({ text: `Generated by Personnel on ${new Date().toISOString().slice(0, 10)}`, fontSize: 7, color: '#999', margin: [0, 24, 0, 0] })
  return renderPdf({ pageSize: 'A4', pageMargins: [48, 56, 48, 56], defaultStyle: { font: 'Roboto', fontSize: 10, lineHeight: 1.25 }, content })
}
