'use strict';

const KEY = 'personnel-design-round-01-v1';
const $ = (selector, root = document) => root.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials = name => name.split(' ').map(p => p[0]).slice(0,2).join('');
const groups = [
  ['Employee records', [['people.view','View employee directory'],['personal.view','View private personal details',true],['employment.edit','Edit employment information'],['departure.start','Start offboarding']]],
  ['Compensation & payroll', [['payroll.summary','View company payroll totals',true],['payroll.individual','View individual payroll',true],['salary.view','View individual salaries',true],['salary.propose','Propose salary changes',true],['salary.approve','Approve salary changes',true],['payroll.approve','Approve payroll',true],['payroll.export','Export payroll',true]]],
  ['Recruitment', [['jobs.view','View company jobs'],['jobs.request','Request a hire'],['jobs.approve','Approve hiring requests'],['jobs.edit','Edit job descriptions'],['jobs.publish','Publish job listings'],['candidates.view','View company applications'],['candidates.review','Record interview feedback'],['offer.approve','Approve offers']]],
  ['Documents & onboarding', [['documents.view','View employment documents',true],['documents.request','Request employee documents'],['tasks.view','View onboarding progress'],['tasks.assign','Assign onboarding tasks'],['tasks.complete','Complete assigned tasks']]],
  ['Equipment & IT', [['it.view','View IT and equipment requests'],['it.assign','Assign requests'],['it.complete','Confirm setup and equipment handoff']]],
  ['Recruitment marketing', [['marketing.view','View approved public job briefs'],['marketing.draft','Draft promotional content'],['marketing.approve','Approve promotional content'],['marketing.publish','Publish company posts']]],
  ['Administration', [['integration.view','View integration status'],['integration.manage','Manage company connections',true],['access.manage','Manage company access',true]]]
];
const labels = Object.fromEntries(groups.flatMap(g=>g[1]).map(p=>[p[0],p[1]]));
const dependencies = {
  'personal.view':['people.view'],'employment.edit':['people.view'],'departure.start':['people.view'],
  'salary.propose':['salary.view'],'salary.approve':['salary.view'],'payroll.approve':['payroll.individual'],
  'payroll.export':['payroll.individual'],'jobs.request':['jobs.view'],'jobs.approve':['jobs.view'],
  'jobs.edit':['jobs.view'],'jobs.publish':['jobs.view'],'candidates.review':['candidates.view'],
  'offer.approve':['candidates.view'],'documents.request':['documents.view'],'tasks.assign':['tasks.view'],
  'tasks.complete':['tasks.view'],'it.assign':['it.view'],'it.complete':['it.view'],
  'marketing.draft':['marketing.view'],'marketing.approve':['marketing.view'],
  'marketing.publish':['marketing.view'],'integration.manage':['integration.view']
};
const presets = {
  'Company Director':['people.view','jobs.view','jobs.request','jobs.approve','candidates.view','tasks.view'],
  'Company HR':['people.view','personal.view','employment.edit','departure.start','jobs.view','jobs.request','jobs.edit','candidates.view','candidates.review','documents.view','documents.request','tasks.view','tasks.assign','tasks.complete','integration.view'],
  'Finance':['people.view','salary.view','payroll.summary','payroll.individual'],
  'IT':['people.view','it.view','it.assign','it.complete','tasks.view','tasks.complete'],
  'Marketing':['marketing.view','marketing.draft'],
  'Hiring Manager':['people.view','jobs.view','jobs.request','candidates.view','candidates.review','tasks.view'],
  'No access':[], 'Custom':[]
};
function seed(){
  const names = [
    ['Alex Morgan','Maya Chen','Oliver Reed','Sofia Martin','James Wilson','Emma Brooks','Noah Bennett','Amelia Ross','Leo Parker','Nora Ellis'],
    ['Daniel Hayes','Isla Turner','Ethan Cole','Mila Foster','Lucas Gray','Eva Reed','Theo Walker','Lily Adams','Owen Scott','Aria Clarke'],
    ['Sarah Miller','Adam Lewis','Chloe Harris','Henry Bell','Grace Young','Oscar King','Ruby Wright','Felix Green','Ella Baker','Jack Stone'],
    ['David Cooper','Zoe Hill','Ben Carter','Lucy Ward','Max Collins','Alice Wood','Sam Hughes','Ivy Allen','Luke Moore','Anna West']
  ];
  const departments = ['Leadership','People','Engineering','Operations','Engineering','Marketing','Finance','Operations','Engineering','Sales'];
  const roles = ['Director','HR Manager','Software Engineer','Operations Lead','Software Engineer','Marketing Specialist','Finance Specialist','Coordinator','Product Designer','Account Manager'];
  const companies = names.map((_,i)=>({id:'c'+(i+1),name:'Company '+String.fromCharCode(65+i),short:String.fromCharCode(65+i),director:names[i][0],color:['#edf3e7','#f4eee4','#eaf0f6','#f2edf5'][i]}));
  const people = names.flatMap((list,i)=>list.map((name,j)=>({id:`p${i}-${j}`,name,company:companies[i].id,title:roles[j],department:departments[j],status:'Active'})));
  const grants = {};
  people.forEach((person,i)=>{const preset=i%10===0?'Company Director':i%10===1?'Company HR':i%10===5?'Marketing':i%10===6?'Finance':'No access';grants[person.id+'|'+person.company]={preset,permissions:[...presets[preset]]};});
  const jobs = companies.map((company,i)=>({id:'j'+i,company:company.id,title:['Operations Coordinator','Product Designer','Account Manager','Software Engineer'][i],manager:company.director,headcount:1,start:'2026-11-02',reason:'Support the team as responsibilities grow and give the role a clear owner.',request:'Submitted',description:'We are looking for a thoughtful, organized teammate who enjoys collaborating across teams. You will own day-to-day work, communicate clearly, and help improve how we operate.',channels:{careers:'Not published',linkedin:'Not connected',other:'Manual handoff'},links:{},promotion:{status:'Not requested',copy:'',url:''},candidates:[{id:'a'+i+'-1',name:['Jamie Taylor','Riley Adams','Casey Lee','Jordan Quinn'][i],source:'Sample careers application',stage:'Interview',note:'Interview completed. Hiring manager feedback is ready for review.'},{id:'a'+i+'-2',name:['Robin Lane','Avery James','Cameron Drew','Charlie Lane'][i],source:'Sample referral',stage:'New',note:'New application awaiting an initial review.'}]}));
  return {version:1,companies,people,grants,jobs,onboarding:[],activity:[]};
}
let state;
try { const saved=JSON.parse(localStorage.getItem(KEY));state=saved?.version===1?saved:seed(); } catch {state=seed();}
let scope='all', page=location.hash.slice(1)||'overview', companyTab='overview', hiringStep='request', jobId='j0', query='';
let editorDraft=null, editorBaseline='', toastTimer;
const main=$('#main'), dialog=$('#editor');
const company = id => state.companies.find(c=>c.id===id);
const person = id => state.people.find(p=>p.id===id);
const inScope = item => scope==='all'||item.company===scope;
const getJob = () => state.jobs.find(j=>j.id===jobId&&inScope(j))||state.jobs.find(inScope);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('Browser storage unavailable. Changes remain in this session only.');return false;}}
function audit(companyId,message){state.activity.unshift({company:companyId,message,at:new Date().toISOString()});}
function commit(companyId,message){audit(companyId,message);const saved=persist();render();if(saved)toast(message);}
function badge(text,tone='gray'){return `<span class="badge ${tone}">${esc(text)}</span>`;}
function btn(text,action,data='',style='secondary small',disabled=false){return `<button class="button ${style}" data-action="${action}" ${data} ${disabled?'disabled':''}>${text}</button>`;}
function avatar(name){return `<span class="avatar" aria-hidden="true">${esc(initials(name))}</span>`;}
function head(eyebrow,title,description,action=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
function metric(label,value,sub){return `<div class="metric"><div class="metric-label">${label}<span class="dot"></span></div><div class="metric-value">${value}</div><div class="metric-sub">${sub}</div></div>`;}
function scopedName(){return scope==='all'?'Holding overview':company(scope).name;}
function navigate(target){page=target;query='';location.hash=target;render();}
function render(){
  if(!['overview','company','people','hiring','onboarding','activity'].includes(page))page='overview';
  $('#company-select').innerHTML=`<option value="all">All companies</option>${state.companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}`;$('#company-select').value=scope;
  const nav=[['overview','◫','Overview'],['company','▦','Company profiles'],['people','♧','People & access'],['hiring','↗','Hiring workspace'],['onboarding','☑','Onboarding'],['activity','◷','Activity']];
  $('#navigation').innerHTML=nav.map(([id,icon,label])=>`<a href="#${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}${id==='hiring'?`<span class="nav-count">${state.jobs.filter(inScope).length}</span>`:''}</a>`).join('');
  main.innerHTML=({overview:overview,company:companyPage,people:peoplePage,hiring:hiringPage,onboarding:onboardingPage,activity:activityPage}[page])();
}
function overview(){
  const people=state.people.filter(inScope), jobs=state.jobs.filter(inScope), plans=state.onboarding.filter(inScope);
  const tasks=plans.reduce((sum,p)=>sum+p.tasks.filter(t=>!t.done).length,0);
  return head('YOUR PEOPLE, CONNECTED',scope==='all'?'A clear view of the whole group.':`${esc(scopedName())}, at a glance.`,'People, hiring decisions, and the next step that needs an owner.',btn('Explore hiring journey <span aria-hidden="true">↗</span>','go-hiring','',''))+
    `<div class="metrics">${metric('People',people.length,'One employing company per person')}${metric('Companies',scope==='all'?4:1,scope==='all'?'One shared holding workspace':'Company-scoped view')}${metric('Hiring requests',jobs.filter(j=>j.request==='Submitted').length,'Awaiting a director’s decision')}${metric('Open onboarding tasks',tasks,plans.length?`${plans.length} onboarding plan(s)`:'Confirm a hire to start a plan')}</div>
    <div class="grid-two"><div><div class="card"><div class="card-head"><div><h2>Needs a decision</h2><p>Clear ownership. One next action.</p></div>${badge('Hiring','green')}</div>${jobs.filter(j=>j.request==='Submitted').map((j,i)=>`<div class="list-row"><span class="list-num">0${i+1}</span><div class="row-text"><strong>${esc(j.title)}</strong><small>${esc(company(j.company).name)} · Requested by ${esc(j.manager)}</small></div>${btn('Review request','open-job',`data-id="${j.id}"`)}</div>`).join('')||'<div class="empty">All hiring requests have been reviewed.</div>'}</div>
    <div class="company-grid">${state.companies.filter(c=>scope==='all'||c.id===scope).map(c=>`<div class="company-card"><div class="company-icon" style="background:${c.color}">${c.short}</div><h3>${esc(c.name)}</h3><p>${esc(c.director)} · Director</p><div class="company-card-bottom"><span>${state.people.filter(p=>p.company===c.id).length} people</span>${btn('Open company →','open-company',`data-id="${c.id}"`,'ghost small')}</div></div>`).join('')}</div></div>
    <div><div class="card"><div class="card-head"><h2>Start with one real workflow</h2></div><div class="card-body"><div class="eyebrow">DESIGN WALKTHROUGH</div><h2 style="margin:12px 0">From a request to a ready first day.</h2><p class="small-copy">Review a director’s request, prepare the job, bring Marketing in, and confirm a candidate. Their onboarding tasks appear automatically.</p>${btn('Open the walkthrough','go-hiring','','gap-top')}</div></div><div class="card"><div class="card-head"><h2>Access is intentional</h2></div><div class="card-body"><p class="small-copy" style="margin-top:0">A Director title does not automatically grant salary or payroll access. You choose their company and capabilities.</p>${btn('Configure a director','director-access','','secondary small')}<div class="inline-note gap-top">Demo grants are editable. This prototype remains in <strong>Admin view</strong>; it does not enforce account access.</div></div></div></div></div>`;
}
function companyPage(){
  if(scope==='all')return head('THE HOLDING','Four companies. One workspace.','Select a company to review its people, access, and hiring activity.')+`<div class="company-grid">${state.companies.map(c=>`<div class="company-card"><div class="company-icon" style="background:${c.color}">${c.short}</div><h2>${c.name}</h2><p>${state.people.filter(p=>p.company===c.id).length} employees · ${esc(c.director)}, Director</p>${btn('Open company profile →','open-company',`data-id="${c.id}"`)}</div>`).join('')}</div>`;
  const c=company(scope),director=state.people.find(p=>p.company===scope&&p.title==='Director');
  const tabs=[['overview','Overview'],['people','People'],['access','Access'],['hiring','Hiring'],['integrations','Integrations']];
  let body='';
  if(companyTab==='overview')body=`<div class="metrics">${metric('People',state.people.filter(inScope).length,'Company employment records')}${metric('Hiring requests',state.jobs.filter(inScope).length,'One sample opening')}${metric('Onboarding',state.onboarding.filter(inScope).length,'Linked to confirmed hires')}${metric('Connected channels',0,'Connections are not configured')}</div><div class="grid-two"><div class="card"><div class="card-head"><h2>Company details</h2></div><div class="card-body"><dl class="detail-grid"><div><dt>Parent organization</dt><dd>Main holding · sample label</dd></div><div><dt>Director</dt><dd>${esc(c.director)}</dd></div><div><dt>Employment structure</dt><dd>One company per employee</dd></div><div><dt>HR workspace</dt><dd>Shared across the holding</dd></div></dl></div></div><div class="card"><div class="card-head"><h2>Director access</h2></div><div class="card-body"><div class="person-cell">${avatar(director.name)}<div><strong>${esc(director.name)}</strong><small>Director · ${c.name}</small></div></div><p class="small-copy">Review the exact capabilities assigned to this company.</p>${btn('Manage permissions','edit-access',`data-person="${director.id}" data-company="${c.id}"`)}</div></div></div>`;
  if(companyTab==='people'||companyTab==='access')body=peopleTable(companyTab==='access');
  if(companyTab==='hiring')body=state.jobs.filter(inScope).map(j=>`<div class="card"><div class="card-head"><div><h2>${esc(j.title)}</h2><p>Requested by ${esc(j.manager)} · ${esc(j.start)}</p></div>${badge(j.request,j.request==='Approved'?'green':'amber')}</div><div class="card-body">${btn('Open hiring workspace →','open-job',`data-id="${j.id}"`,'')}</div></div>`).join('');
  if(companyTab==='integrations')body=`<div class="card"><div class="card-head"><div><h2>Company connections</h2><p>Every destination belongs to ${c.name}.</p></div></div><div class="card-body">${[['LinkedIn company page','Separate authorization for promotional posts and recruitment APIs.'],['Recruitment platforms','Provider availability and your existing accounts must be confirmed.'],['Leave system','Your existing system stays responsible for requests and balances.']].map(([name,description])=>`<div class="channel"><div class="channel-top"><h3>${name}</h3>${badge('Not connected','amber')}</div><p>${description}</p>${btn('View connection requirements','connection',`data-provider="${esc(name)}"`)}</div>`).join('')}<div class="inline-note">No account has been connected. The prototype does not request credentials or publish externally.</div></div></div>`;
  return `<div class="eyebrow" style="margin-bottom:17px">HOLDING / COMPANY PROFILE</div><div class="company-banner"><div class="company-icon" style="background:${c.color}">${c.short}</div><div><h1>${c.name}</h1><p>Part of the holding · ${state.people.filter(inScope).length} people · Sample company</p></div></div><div class="tabs" role="tablist" aria-label="Company profile">${tabs.map(([id,label])=>`<button class="tab ${companyTab===id?'active':''}" role="tab" aria-selected="${companyTab===id}" data-action="company-tab" data-tab="${id}">${label}</button>`).join('')}</div>${body}`;
}
function peopleRows(){
  return state.people.filter(inScope).filter(p=>`${p.name} ${p.title} ${p.department} ${company(p.company).name}`.toLowerCase().includes(query.toLowerCase())).map(p=>{
    const grant=state.grants[p.id+'|'+p.company]||{preset:'No access',permissions:[]};
    return `<tr><td><div class="person-cell">${avatar(p.name)}<div><strong>${esc(p.name)}</strong><small>${esc(p.title)}</small></div></div></td><td>${company(p.company).name}</td><td>${esc(p.department)}</td><td>${badge(p.status,p.status==='Active'?'green':'blue')}</td><td>${esc(grant.preset)}<div class="source" style="margin-top:5px">${grant.permissions.length} capabilities</div></td><td>${btn('Manage access','edit-access',`data-person="${p.id}" data-company="${p.company}"`)}</td></tr>`;
  }).join('')||'<tr><td colspan="6" class="empty">No people match your search.</td></tr>';
}
function peopleTable(access=false){return `<div class="card"><div class="card-head"><div><h2>${access?'People & permissions':'Employee directory'}</h2><p>Company grants are separate from job titles.</p></div><input class="search" id="people-search" aria-label="Search employees" placeholder="Search name, role, department…" value="${esc(query)}"></div><div class="table-wrap"><table><thead><tr><th>Person / title</th><th>Company</th><th>Department</th><th>Employment</th><th>Access preset</th><th>Action</th></tr></thead><tbody id="people-rows">${peopleRows()}</tbody></table></div></div>`;}
function peoplePage(){return head('PEOPLE & ACCESS','The right access for every person.','Select a person, choose a company, and configure their capabilities.')+`<div class="inline-note" style="margin-bottom:22px"><strong>Admin workspace.</strong> You can configure all four companies. An employee’s job title does not grant permissions.</div>`+peopleTable(true);}
function openAccess(personId,companyId){
  const grant=state.grants[personId+'|'+companyId]||{preset:'No access',permissions:[]};
  editorDraft={personId,companyId,preset:grant.preset,permissions:[...grant.permissions]};
  editorBaseline=JSON.stringify(editorDraft);renderAccess();dialog.showModal();
}
function renderAccess(){
  const d=editorDraft,p=person(d.personId);
  dialog.innerHTML=`<div class="dialog-header"><div><div class="eyebrow">COMPANY ACCESS</div><h2 id="dialog-title">Choose what ${esc(p.name.split(' ')[0])} can do.</h2><p>Job title: ${esc(p.title)} · Employed by ${company(p.company).name}</p></div><button class="close-button" data-action="close-dialog" aria-label="Close permissions">×</button></div><div class="dialog-layout"><div class="permission-main"><div class="form-grid"><div class="field"><label for="access-company">Company access applies to</label><select id="access-company">${state.companies.map(c=>`<option value="${c.id}" ${c.id===d.companyId?'selected':''}>${c.name}</option>`).join('')}</select></div><div class="field"><label for="access-preset">Start from a preset</label><select id="access-preset">${Object.keys(presets).map(key=>`<option ${key===d.preset?'selected':''}>${key}</option>`).join('')}</select></div></div><p class="small-copy" style="margin:0 0 17px">Expand a group to adjust capabilities. Selecting an action also enables the viewing access it requires.</p>${groups.map(([title,items],i)=>`<details class="permission-group" ${i<2?'open':''}><summary>${title}<span data-group-count="${esc(title)}">${items.filter(([id])=>d.permissions.includes(id)).length}/${items.length}</span></summary>${items.map(([id,label,sensitive])=>`<label class="permission-check"><input type="checkbox" data-permission="${id}" ${d.permissions.includes(id)?'checked':''}><span>${label}</span>${sensitive?'<small>Sensitive</small>':''}</label>`).join('')}</details>`).join('')}</div><aside class="permission-preview"><div class="eyebrow">EFFECTIVE ACCESS PREVIEW</div><div class="preview-person">${avatar(p.name)}<div><strong>${esc(p.name)}</strong><small>${company(d.companyId).name} only</small></div></div><div id="access-preview"></div></aside></div><div class="dialog-footer"><small>Saved as a demo grant. Live account enforcement is not implemented.</small><div class="actions">${btn('Cancel','close-dialog')}${btn('Save permissions','save-access','','')}</div></div>`;
  updateAccessPreview();
}
function updateAccessPreview(){
  const d=editorDraft, set=new Set(d.permissions);
  $('#access-preview',dialog).innerHTML=`<h3>${set.size?'Allowed in this company':'No access to this company'}</h3>${set.size?`<ul class="preview-list">${d.permissions.map(id=>`<li>${labels[id]}</li>`).join('')}</ul>`:'<p class="small-copy">This person has no capabilities granted here.</p>'}<div class="preview-warning">${!set.has('salary.view')?'Individual salaries remain hidden.<br>':''}${!set.has('payroll.export')?'Payroll export is not allowed.<br>':''}${!set.has('access.manage')?'Cannot change other people’s access.<br>':''}Other companies keep their own separate grants.</div>`;
  groups.forEach(([title,items])=>{const el=dialog.querySelector(`[data-group-count="${title}"]`);if(el)el.textContent=`${items.filter(([id])=>set.has(id)).length}/${items.length}`;});
  $('[data-action="save-access"]',dialog).disabled=JSON.stringify(d)===editorBaseline;
}
function normalizePermission(id,on){
  const set=new Set(editorDraft.permissions);
  function add(key){set.add(key);(dependencies[key]||[]).forEach(add);}
  if(on)add(id);else {set.delete(id);let again=true;while(again){again=false;for(const key of set){if((dependencies[key]||[]).some(dep=>!set.has(dep))){set.delete(key);again=true;}}}}
  editorDraft.permissions=Object.keys(labels).filter(key=>set.has(key));editorDraft.preset='Custom';
  dialog.querySelectorAll('[data-permission]').forEach(input=>input.checked=set.has(input.dataset.permission));$('#access-preset').value='Custom';updateAccessPreview();
}
function closeDialog(force=false){if(!force&&editorDraft&&JSON.stringify(editorDraft)!==editorBaseline&&!confirm('Discard unsaved permission changes?'))return;editorDraft=null;dialog.close();}
function modal(title,content,footer=''){
  editorDraft=null;dialog.innerHTML=`<div class="dialog-header"><div><div class="eyebrow">DESIGN WALKTHROUGH</div><h2 id="dialog-title">${title}</h2></div><button class="close-button" data-action="close-dialog" aria-label="Close dialog">×</button></div><div class="modal-body">${content}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}`;dialog.showModal();
}
function hiringPage(){
  const j=getJob();jobId=j.id;
  const steps=[['request','01','Hiring request'],['job','02','Job & channels'],['promotion','03','Promotion'],['candidates','04','Applications'],['handoff','05','Hire & onboarding']];
  return head('RECRUITMENT / '+company(j.company).name.toUpperCase(),'One role. Every handoff connected.','Follow the sample role from a director’s request to the employee’s first day.',`<label class="field" style="margin:0"><span class="field-label">Sample hiring workspace</span><select id="job-select">${state.jobs.filter(inScope).map(job=>`<option value="${job.id}" ${job.id===j.id?'selected':''}>${company(job.company).name} · ${esc(job.title)}</option>`).join('')}</select></label>`)+
    `<div class="journey" aria-label="Hiring journey">${steps.map(([id,n,label])=>`<button data-action="hiring-step" data-step="${id}" class="${hiringStep===id?'active':''}" ${hiringStep===id?'aria-current="step"':''}><span>STEP ${n}</span>${label}</button>`).join('')}</div><div class="grid-two"><div>${({request:requestView,job:jobView,promotion:promotionView,candidates:candidatesView,handoff:handoffView}[hiringStep])(j)}</div><div><div class="card"><div class="card-head"><h2>The hiring brief</h2></div><div class="card-body"><div class="eyebrow">${company(j.company).name}</div><h2 style="font-size:22px;margin:12px 0 18px">${esc(j.title)}</h2><dl class="detail-grid"><div><dt>Hiring manager</dt><dd>${esc(j.manager)}</dd></div><div><dt>Headcount requested</dt><dd>${j.headcount}</dd></div><div><dt>Target start</dt><dd>${esc(j.start)}</dd></div><div><dt>Request status</dt><dd>${badge(j.request,j.request==='Approved'?'green':'amber')}</dd></div></dl></div></div><div class="inline-note"><strong>Keep the handoffs honest.</strong><br>Job approval, channel publication, a promotional post, and hiring a person are separate actions with separate results.</div><div class="card gap-top"><div class="card-head"><h2>Recent activity</h2></div>${activityRows(j.company,4)}</div></div></div>`;
}
function requestView(j){return `<div class="card"><div class="card-head"><div><h2>Review the hiring request</h2><p>Requested by ${esc(j.manager)} · Company Director</p></div>${badge(j.request,j.request==='Approved'?'green':'amber')}</div><div class="card-body">${j.request==='Changes requested'?`<div class="inline-note" style="margin-bottom:20px"><strong>Changes requested:</strong> ${esc(j.changeReason)}</div>`:''}<form id="request-form"><div class="form-grid"><div class="field"><label for="job-title">Job title</label><input id="job-title" name="title" value="${esc(j.title)}" required maxlength="100"></div><div class="field"><label for="job-start">Target start date</label><input id="job-start" name="start" type="date" value="${esc(j.start)}" required></div></div><div class="field"><label for="job-reason">Why we need this role</label><textarea id="job-reason" name="reason" required maxlength="2000">${esc(j.reason)}</textarea></div><div class="actions"><button type="submit" class="button secondary small" ${j.request==='Approved'?'disabled':''}>Save request details</button></div></form><div class="review-box">You are reviewing as <strong>Admin</strong>. In the live workflow, the company’s configured approver receives this decision. Approval does not publish the job.</div><div class="actions">${btn(j.request==='Approved'?'Approved':'Approve request','approve-request','','',j.request==='Approved')}${btn('Request changes','request-changes','', 'secondary',j.request==='Approved')}${j.request==='Approved'?btn('Prepare job →','hiring-step','data-step="job"','secondary'):''}</div></div></div>`;}
function jobView(j){return `<div class="card"><div class="card-head"><div><h2>Prepare the job</h2><p>One approved description, separate publishing destinations.</p></div></div><div class="card-body"><form id="description-form"><div class="field"><label for="description">Public job description</label><textarea id="description" name="description" required maxlength="6000" style="min-height:150px">${esc(j.description)}</textarea></div><button class="button secondary small" type="submit">Save description draft</button></form></div></div><div class="card"><div class="card-head"><h2>Publishing channels</h2>${badge(company(j.company).name,'green')}</div><div class="card-body"><div class="channel"><div class="channel-top"><h3>Company careers page</h3>${badge(j.channels.careers,j.channels.careers==='Demo live'?'green':'gray')}</div><p>Preview the branded application experience. Publishing here updates the prototype only.</p><div class="actions">${btn('Preview careers page','careers-preview')}${btn(j.channels.careers==='Demo live'?'Close demo listing':'Publish demo listing','publish-careers','','',j.request!=='Approved')}</div>${j.request!=='Approved'?'<p>Approve the hiring request first.</p>':''}</div><div class="channel"><div class="channel-top"><h3>LinkedIn · ${company(j.company).name}</h3>${badge(j.channels.linkedin,'amber')}</div><p>Recruitment publishing and applicant delivery require approved API access. A company-page connection alone is not sufficient.</p>${btn('Review integration requirements','connection','data-provider="LinkedIn recruitment"')}</div><div class="channel"><div class="channel-top"><h3>Other recruitment platform</h3>${badge(j.channels.other,j.links.other?'blue':'gray')}</div><p>Prepare the approved copy, publish on your chosen platform, and record the listing URL. No automatic sync is implied.</p>${j.links.other?`<div class="code-link">${esc(j.links.other)}</div>`:''}${btn('Record manual publication','manual-publication','','secondary small',j.request!=='Approved')}</div></div></div>`;}
function promotionView(j){const p=j.promotion;return `<div class="card"><div class="card-head"><div><h2>Recruitment promotion</h2><p>Marketing sees the approved public brief, not private candidate records.</p></div>${badge(p.status,p.status==='Published manually'?'green':'amber')}</div><div class="card-body"><div class="detail-grid"><div><span class="field-label">Destination</span><p class="small-copy">${company(j.company).name} · LinkedIn company page</p></div><div><span class="field-label">Requested owner</span><p class="small-copy">Company Marketing team</p></div></div>${p.status==='Not requested'?`<p class="small-copy">Create a promotion brief after approving the hiring request. Marketing can prepare copy and creative, then ask for review.</p>${btn('Request promotion','request-promotion','','',j.request!=='Approved')}`:`<form id="promotion-form"><div class="field"><label for="promotion-copy">Promotional copy</label><textarea id="promotion-copy" name="copy" required maxlength="3000" style="min-height:150px" ${p.status==='Published manually'?'readonly':''}>${esc(p.copy)}</textarea><small>Editing approved content returns it to Draft for another review.</small></div><div class="actions"><button type="submit" class="button secondary small" ${p.status==='Published manually'?'disabled':''}>Save draft</button>${btn('Submit for review','review-promotion','','secondary small',!p.copy||!['Requested','Draft'].includes(p.status))}${btn('Approve content','approve-promotion','','',p.status!=='In review')}</div></form><div class="review-box">Demo uses your Admin session to walk through each role. In the live system, drafting, approving, and publishing will be separate grants.</div>${p.status==='Approved'?btn('Record manual post','manual-promotion','',''):''}${p.url?`<div class="code-link">${esc(p.url)}</div>`:''}`}</div></div>`;}
function candidatesView(j){return `<div class="card"><div class="card-head"><div><h2>Applications</h2><p>${j.candidates.length} sample application(s) · ${company(j.company).name}</p></div>${btn('Preview application form','careers-preview')}</div><div class="card-body">${j.candidates.map(a=>`<div class="candidate"><div class="channel-top"><div class="person-cell">${avatar(a.name)}<div><strong>${esc(a.name)}</strong><small>${esc(a.source)}</small></div></div>${badge(a.stage,a.stage==='Hired'?'green':a.stage==='Rejected'?'red':'blue')}</div><p>${esc(a.note)}</p><div class="actions">${btn('Review application','candidate-detail',`data-candidate="${a.id}"`)}${!['Hired','Rejected'].includes(a.stage)?`${btn(a.stage==='New'?'Move to interview':a.stage==='Interview'?'Prepare offer':a.stage==='Offer'?'Record acceptance':'Confirm hire','candidate-next',`data-candidate="${a.id}"`,'',j.request!=='Approved')}${btn('Reject','reject-candidate',`data-candidate="${a.id}"`,'ghost small')}`:''}</div></div>`).join('')}</div></div>`;}
function handoffView(j){const plans=state.onboarding.filter(p=>p.job===j.id);return `<div class="card"><div class="card-head"><h2>From hired to ready</h2></div><div class="card-body">${plans.length?plans.map(p=>planSummary(p)).join(''):`<div class="empty"><h3>The next teammate starts here.</h3><p>Review a candidate, record offer acceptance, then confirm the employee details. Their onboarding plan appears here automatically.</p>${btn('Review applications →','hiring-step','data-step="candidates"','')}</div>`}<div class="inline-note">A confirmed hire creates one employee and one onboarding plan in ${company(j.company).name}. Repeating the action must never create duplicates.</div></div></div>`;}
function careersPreview(){const j=getJob();modal(`${esc(company(j.company).name)} · Careers preview`,`<div class="eyebrow">SAMPLE CAREERS PAGE · ${j.channels.careers==='Demo live'?'DEMO LISTING OPEN':'PREVIEW ONLY'}</div><h2 style="font-size:26px;margin:15px 0">${esc(j.title)}</h2><p class="small-copy" style="white-space:pre-wrap">${esc(j.description)}</p><div class="inline-note">This is a local application preview. Use a made-up name; no data is sent to a company or recruitment provider.</div><form id="application-form" class="gap-top"><div class="field"><label for="applicant-name">Sample applicant name</label><input id="applicant-name" name="name" required maxlength="80" placeholder="e.g. Morgan Ellis"></div><button class="button" type="submit" ${j.channels.careers!=='Demo live'?'disabled':''}>Submit demo application</button>${j.channels.careers!=='Demo live'?'<p class="small-copy">Publish the demo careers listing first to test application intake.</p>':''}</form>`);}
function openHire(candidateId){
  const j=getJob(),a=j.candidates.find(a=>a.id===candidateId);if(j.candidates.filter(c=>c.employeeId).length>=j.headcount){toast('All requested positions are filled.');return;}if(a.employeeId){toast('This candidate already has an employee record.');return;}
  modal('Confirm the hire',`<form id="hire-form" data-candidate="${a.id}"><div class="inline-note">Review the handoff before creating the employee. Cancel leaves this candidate at Offer accepted.</div><div class="form-grid gap-top"><div class="field"><label for="hire-name">Full name</label><input id="hire-name" name="name" value="${esc(a.name)}" required maxlength="80"></div><div class="field"><label for="hire-company">Employing company</label><input id="hire-company" value="${company(j.company).name}" readonly></div><div class="field"><label for="hire-title">Position</label><input id="hire-title" name="title" value="${esc(j.title)}" required maxlength="100"></div><div class="field"><label for="hire-date">Start date</label><input id="hire-date" name="start" type="date" value="${esc(j.start)}" required></div><div class="field"><label for="hire-department">Department</label><select id="hire-department" name="department" required><option value="">Choose department</option>${['Operations','Engineering','Marketing','Finance','Sales','People'].map(d=>`<option>${d}</option>`).join('')}</select></div><div class="field"><label for="hire-manager">Manager</label><input id="hire-manager" name="manager" value="${esc(j.manager)}" required maxlength="80"></div></div><div class="review-box">Create a Pre-start employee, link this application, and assign the standard onboarding plan. No login, payroll enrollment, email, or external account is created in this prototype.</div><div class="actions"><button class="button" type="submit">Confirm hire & create plan</button>${btn('Cancel','close-dialog')}</div></form>`);
}
function planSummary(p){const done=p.tasks.filter(t=>t.done).length,critical=p.tasks.filter(t=>t.critical&&!t.done).length;return `<div class="channel"><div class="channel-top"><div class="person-cell">${avatar(p.name)}<div><strong>${esc(p.name)}</strong><small>${company(p.company).name} · Starts ${esc(p.start)}</small></div></div>${badge(critical?`${critical} readiness gaps`:'Ready for day one',critical?'amber':'green')}</div><div class="progress"><span style="width:${done/p.tasks.length*100}%"></span></div><p>${done} of ${p.tasks.length} tasks completed · ${esc(p.manager)}, Manager</p>${btn('Open onboarding plan','open-onboarding',`data-id="${p.id}"`)}</div>`;}
function onboardingPage(){const plans=state.onboarding.filter(inScope);return head('HR OPERATIONS / ONBOARDING','Make the first day feel prepared.','Documents, equipment, accounts, and the manager’s welcome—all with an owner.')+(plans.length?plans.map(p=>`<div class="card" id="plan-${p.id}"><div class="card-head"><div><h2>${esc(p.name)}</h2><p>${company(p.company).name} · ${esc(p.title)} · Starts ${esc(p.start)}</p></div>${badge(p.tasks.some(t=>t.critical&&!t.done)?'Needs preparation':'Ready for day one',p.tasks.some(t=>t.critical&&!t.done)?'amber':'green')}</div><div class="card-body">${p.tasks.map(t=>`<div class="task ${t.done?'done':''}"><span class="task-status" aria-hidden="true">${t.done?'✓':'○'}</span><div class="row-text"><strong>${esc(t.title)}</strong><small>${esc(t.owner)} · ${esc(t.due)}${t.critical?' · Required before start':''}</small></div>${btn(t.done?'Reopen':'Mark complete','toggle-task',`data-plan="${p.id}" data-task="${t.id}"`,t.done?'ghost small':'secondary small')}</div>`).join('')}<p class="small-copy">Completion here is a manual demo confirmation. Live document review and IT delivery will require their own recorded results.</p></div></div>`).join(''):`<div class="card"><div class="empty"><h3>No upcoming starters yet.</h3><p>Confirm a sample hire to see their company-specific onboarding plan.</p>${btn('Open hiring journey','go-hiring','','')}</div></div>`);}
function activityRows(companyId=null,limit=30){const entries=state.activity.filter(a=>companyId?a.company===companyId:inScope(a)).slice(0,limit);return entries.map(a=>`<div class="activity"><i aria-hidden="true"></i><div><p>${esc(a.message)}</p><small>${company(a.company).name} · Admin (demo) · ${new Date(a.at).toLocaleString()}</small></div></div>`).join('')||'<div class="empty">Actions you take in the demo will appear here.</div>';}
function activityPage(){return head('WORKSPACE / HISTORY','A record of the important actions.','Permission changes, approvals, hires, and task completion in the current company scope.')+`<div class="card"><div class="card-head"><h2>Activity history</h2>${badge('Local demo history')}</div>${activityRows()}</div>`;}

document.addEventListener('click',event=>{
  const target=event.target.closest('[data-action]');if(!target)return;
  const {action,id,tab,step,candidate:aid}=target.dataset;
  const j=getJob();
  if(action==='go-hiring'){hiringStep='request';navigate('hiring');}
  else if(action==='open-company'){scope=id;companyTab='overview';navigate('company');}
  else if(action==='company-tab'){companyTab=tab;query='';render();}
  else if(action==='open-job'){jobId=id;scope=state.jobs.find(j=>j.id===id).company;hiringStep='request';navigate('hiring');}
  else if(action==='hiring-step'){hiringStep=step;render();}
  else if(action==='director-access'){const c=scope==='all'?'c1':scope;openAccess(state.people.find(p=>p.company===c&&p.title==='Director').id,c);}
  else if(action==='edit-access'){openAccess(target.dataset.person,target.dataset.company);}
  else if(action==='close-dialog'){closeDialog();}
  else if(action==='save-access'){
    const d=editorDraft,previous=state.grants[d.personId+'|'+d.companyId]?.permissions||[];
    const added=d.permissions.filter(k=>!previous.includes(k)),removed=previous.filter(k=>!d.permissions.includes(k));
    state.grants[d.personId+'|'+d.companyId]={preset:d.preset,permissions:[...d.permissions]};
    const message=`Updated ${person(d.personId).name}’s access.${added.length?' Added: '+added.map(k=>labels[k]).join(', ')+'.':''}${removed.length?' Removed: '+removed.map(k=>labels[k]).join(', ')+'.':''}`;
    closeDialog(true);commit(d.companyId,message);
  }
  else if(action==='approve-request'){j.request='Approved';commit(j.company,`Approved hiring request: ${j.title}.`);}
  else if(action==='request-changes'){modal('Request changes',`<form id="changes-form"><div class="field"><label for="change-reason">What should the requester update?</label><textarea id="change-reason" name="reason" required maxlength="1000"></textarea></div><button type="submit" class="button">Record change request</button></form>`);}
  else if(action==='connection'){const provider=target.dataset.provider;modal('Connection requirements',`<h3>${esc(provider)} · ${esc(scope==='all'?company(j.company).name:scopedName())}</h3><p class="small-copy">This design does not connect external accounts. The live flow will identify the company account, verify the authorized user, and show supported capabilities.</p><div class="review-box">${provider.includes('LinkedIn')?'LinkedIn recruitment APIs require approved partner/developer access. Company promotional posts use separate Community Management access and company-page permissions.':provider==='Leave system'?'Confirm the existing provider, employee identifiers, data direction, and available API. Leave requests and balances remain in that system.':'Confirm the provider, employer account, integration eligibility, and supported publishing or application-delivery method.'}</div><p class="small-copy">Connection statuses to design: Not connected, Authorization required, Connected, Sync issue, and Disconnected. No credentials are collected in this prototype.</p>`);}
  else if(action==='careers-preview')careersPreview();
  else if(action==='publish-careers'){if(j.request!=='Approved')return;j.channels.careers=j.channels.careers==='Demo live'?'Closed':'Demo live';commit(j.company,`${j.channels.careers==='Demo live'?'Published':'Closed'} local demo careers listing: ${j.title}.`);}
  else if(action==='manual-publication'||action==='manual-promotion'){
    modal(action==='manual-promotion'?'Record a manually published post':'Record a manually published listing',`<form id="manual-form" data-kind="${action==='manual-promotion'?'promotion':'job'}"><div class="inline-note">Record a URL after someone has published externally. This action does not publish or verify content.</div><div class="field gap-top"><label for="manual-url">Published URL (HTTPS)</label><input id="manual-url" name="url" type="url" placeholder="https://example.com/job-or-post" required></div><button type="submit" class="button">Save publication record</button></form>`);
  }
  else if(action==='request-promotion'){if(j.request!=='Approved')return;j.promotion.status='Requested';j.promotion.copy=`We’re hiring a ${j.title} at ${company(j.company).name}. Join a team that values thoughtful work and collaboration. Explore the role on our company careers page.`;commit(j.company,`Requested Marketing promotion for ${j.title}.`);}
  else if(action==='review-promotion'){j.promotion.status='In review';commit(j.company,`Submitted promotional copy for review: ${j.title}.`);}
  else if(action==='approve-promotion'){j.promotion.status='Approved';commit(j.company,`Approved promotional copy for ${j.title}.`);}
  else if(action==='candidate-detail'){const a=j.candidates.find(a=>a.id===aid);modal('Application review',`<div class="person-cell">${avatar(a.name)}<div><strong>${esc(a.name)}</strong><small>${company(j.company).name} · ${esc(j.title)}</small></div></div><form id="candidate-note-form" data-candidate="${a.id}"><div class="field gap-top"><label for="candidate-note">Review notes / next action</label><textarea id="candidate-note" name="note" required maxlength="2000">${esc(a.note)}</textarea></div><p class="small-copy">Synthetic application for workflow review. No résumé evaluation or automated ranking is performed.</p><button type="submit" class="button">Save review note</button></form>`);}
  else if(action==='candidate-next'){
    if(j.request!=='Approved')return;const a=j.candidates.find(a=>a.id===aid);
    if(a.stage==='Offer accepted'){openHire(aid);return;}
    const next={New:'Interview',Interview:'Offer',Offer:'Offer accepted'}[a.stage];if(!next)return;a.stage=next;commit(j.company,`${a.name}: ${next}.`);
  }
  else if(action==='reject-candidate'){const a=j.candidates.find(a=>a.id===aid);modal('Record a rejection',`<form id="rejection-form" data-candidate="${a.id}"><p class="small-copy">${esc(a.name)} · ${esc(j.title)}. This records the decision only; no message is sent.</p><div class="field"><label for="rejection-reason">Decision reason</label><textarea id="rejection-reason" name="reason" required maxlength="1000"></textarea></div><button type="submit" class="button danger">Record rejection</button></form>`);}
  else if(action==='open-onboarding'){navigate('onboarding');document.getElementById('plan-'+id)?.scrollIntoView({behavior:'smooth',block:'start'});}
  else if(action==='toggle-task'){const p=state.onboarding.find(p=>p.id===target.dataset.plan),t=p.tasks.find(t=>t.id===target.dataset.task);t.done=!t.done;commit(p.company,`${t.done?'Completed':'Reopened'} ${t.title.toLowerCase()} for ${p.name}.`);}
});
document.addEventListener('change',event=>{
  const target=event.target;
  if(target.id==='company-select'){scope=target.value;query='';render();}
  else if(target.id==='job-select'){jobId=target.value;render();}
  else if(target.id==='access-company'){
    if(JSON.stringify(editorDraft)!==editorBaseline&&!confirm('Discard unsaved changes before changing company?')){target.value=editorDraft.companyId;return;}
    const c=target.value,p=editorDraft.personId;const grant=state.grants[p+'|'+c]||{preset:'No access',permissions:[]};editorDraft={personId:p,companyId:c,preset:grant.preset,permissions:[...grant.permissions]};editorBaseline=JSON.stringify(editorDraft);renderAccess();
  }
  else if(target.id==='access-preset'){editorDraft.preset=target.value;editorDraft.permissions=target.value==='Custom'?editorDraft.permissions:[...presets[target.value]];renderAccess();}
  else if(target.dataset.permission){normalizePermission(target.dataset.permission,target.checked);}
});
document.addEventListener('input',event=>{if(event.target.id==='people-search'){query=event.target.value;$('#people-rows').innerHTML=peopleRows();}});
document.addEventListener('submit',event=>{
  event.preventDefault();const form=event.target,fd=new FormData(form),j=getJob();const value=name=>String(fd.get(name)||'').trim();
  if(form.id==='request-form'){if(j.request==='Approved')return;j.title=value('title');j.reason=value('reason');j.start=value('start');j.request='Submitted';commit(j.company,`Saved hiring request: ${j.title}.`);}
  else if(form.id==='description-form'){j.description=value('description');if(j.channels.careers==='Demo live')j.channels.careers='Draft changed';commit(j.company,`Saved description draft for ${j.title}.`);}
  else if(form.id==='changes-form'){j.request='Changes requested';j.changeReason=value('reason');closeDialog(true);commit(j.company,`Requested changes to ${j.title}: ${j.changeReason}`);}
  else if(form.id==='promotion-form'){j.promotion.copy=value('copy');j.promotion.status='Draft';commit(j.company,`Saved promotional draft for ${j.title}.`);}
  else if(form.id==='manual-form'){
    let url;try{url=new URL(value('url'));if(url.protocol!=='https:')throw Error();}catch{form.querySelector('input').setCustomValidity('Enter a valid HTTPS URL.');form.querySelector('input').reportValidity();form.querySelector('input').oninput=()=>form.querySelector('input').setCustomValidity('');return;}
    if(form.dataset.kind==='promotion'){j.promotion.url=url.href;j.promotion.status='Published manually';}else{j.links.other=url.href;j.channels.other='Published manually';}closeDialog(true);commit(j.company,`Recorded manual ${form.dataset.kind==='promotion'?'post':'job publication'} for ${j.title}.`);
  }
  else if(form.id==='application-form'){if(j.channels.careers!=='Demo live')return;j.candidates.push({id:crypto.randomUUID(),name:value('name'),source:'Demo careers form',stage:'New',note:'New demo application. Assign the next review action.'});closeDialog(true);hiringStep='candidates';commit(j.company,`Received a demo application for ${j.title}.`);}
  else if(form.id==='candidate-note-form'){const a=j.candidates.find(a=>a.id===form.dataset.candidate);a.note=value('note');closeDialog(true);commit(j.company,`Updated review notes for ${a.name}.`);}
  else if(form.id==='rejection-form'){const a=j.candidates.find(a=>a.id===form.dataset.candidate);a.stage='Rejected';a.note='Decision reason: '+value('reason');closeDialog(true);commit(j.company,`Recorded rejection for ${a.name}. No message sent.`);}
  else if(form.id==='hire-form'){
    const a=j.candidates.find(a=>a.id===form.dataset.candidate);if(a.employeeId||j.candidates.filter(c=>c.employeeId).length>=j.headcount){closeDialog(true);toast('This hire is already recorded or the requested headcount is filled.');return;}
    const employeeId=crypto.randomUUID();state.people.push({id:employeeId,name:value('name'),title:value('title'),department:value('department'),company:j.company,status:'Pre-start',start:value('start'),manager:value('manager')});state.grants[employeeId+'|'+j.company]={preset:'No access',permissions:[]};a.employeeId=employeeId;a.stage='Hired';
    state.onboarding.push({id:crypto.randomUUID(),job:j.id,employeeId,company:j.company,name:value('name'),title:value('title'),manager:value('manager'),start:value('start'),tasks:[
      {id:'contract',title:'Employment documents reviewed',owner:'HR',due:'Before start date',critical:true,done:false},
      {id:'equipment',title:'Laptop and equipment handed over',owner:'IT',due:'Before start date',critical:true,done:false},
      {id:'accounts',title:'Work account and access confirmed',owner:'IT',due:'Before start date',critical:true,done:false},
      {id:'welcome',title:'First-day details shared',owner:'HR',due:'Before start date',critical:true,done:false},
      {id:'intro',title:'Team introduction completed',owner:value('manager'),due:'First day',critical:false,done:false}
    ]});closeDialog(true);hiringStep='handoff';commit(j.company,`Confirmed ${a.name}’s hire and created one onboarding plan.`);
  }
});
dialog.addEventListener('cancel',event=>{event.preventDefault();closeDialog();});
$('#reset-demo').addEventListener('click',()=>{if(confirm('Reset all prototype edits, grants, and hires to the sample data?')){state=seed();scope='all';companyTab='overview';hiringStep='request';jobId='j0';persist();navigate('overview');toast('Demo reset to 40 people across four companies.');}});
window.addEventListener('hashchange',()=>{page=location.hash.slice(1)||'overview';query='';render();});
render();
